"""
Minimal knowledge base with sample recipes for the food KB answerer.
"""

from src.models.contracts import Ingredient, Recipe

# Sample recipes for the knowledge base
RECIPES = [
    Recipe(
        id="001",
        name="Spicy Sichuan Noodles",
        description="Traditional Sichuan-style spicy noodles with numbing heat",
        cuisine_type="Chinese",
        difficulty="medium",
        prep_time="15 minutes",
        cook_time="10 minutes",
        servings=2,
        ingredients=[
            Ingredient(name="fresh noodles", amount="200", unit="g"),
            Ingredient(name="Sichuan peppercorns", amount="1", unit="tsp"),
            Ingredient(name="chili oil", amount="2", unit="tbsp"),
            Ingredient(name="garlic", amount="3", unit="cloves"),
            Ingredient(name="ginger", amount="1", unit="inch"),
            Ingredient(name="soy sauce", amount="2", unit="tbsp"),
            Ingredient(name="rice vinegar", amount="1", unit="tbsp"),
            Ingredient(name="scallions", amount="2", unit="stalks"),
            Ingredient(name="sesame oil", amount="1", unit="tsp"),
        ],
        instructions=[
            "Boil noodles according to package instructions until al dente",
            "Toast Sichuan peppercorns in a dry pan until fragrant",
            "Grind peppercorns to a fine powder",
            "Mince garlic and ginger",
            "Heat chili oil in a wok or large pan",
            "Add garlic and ginger, stir-fry for 30 seconds",
            "Add soy sauce and rice vinegar",
            "Drain noodles and add to the pan",
            "Toss noodles with the sauce",
            "Garnish with scallions and sesame oil",
            "Sprinkle with ground Sichuan peppercorns",
        ],
        tags=["spicy", "noodles", "sichuan", "chinese", "hot", "numbing"],
        spice_level="extra-hot",
    ),
    Recipe(
        id="002",
        name="Miso Ramen",
        description="Comforting Japanese miso ramen with soft-boiled egg",
        cuisine_type="Japanese",
        difficulty="easy",
        prep_time="20 minutes",
        cook_time="15 minutes",
        servings=2,
        ingredients=[
            Ingredient(name="ramen noodles", amount="2", unit="packages"),
            Ingredient(name="miso paste", amount="3", unit="tbsp"),
            Ingredient(name="chicken broth", amount="4", unit="cups"),
            Ingredient(name="soft-boiled eggs", amount="2", unit="pieces"),
            Ingredient(name="nori sheets", amount="2", unit="sheets"),
            Ingredient(name="scallions", amount="2", unit="stalks"),
            Ingredient(name="corn kernels", amount="1/2", unit="cup"),
            Ingredient(name="butter", amount="1", unit="tbsp"),
        ],
        instructions=[
            "Boil eggs for 6 minutes, then cool in ice water",
            "Heat chicken broth in a pot",
            "Whisk in miso paste until dissolved",
            "Cook ramen noodles separately",
            "Add butter to the broth",
            "Place noodles in bowls",
            "Pour hot broth over noodles",
            "Top with halved soft-boiled eggs",
            "Add corn kernels and sliced scallions",
            "Garnish with nori sheets",
        ],
        tags=["ramen", "miso", "japanese", "comfort", "mild", "noodles"],
        spice_level="mild",
    ),
    Recipe(
        id="003",
        name="Spicy Pad Thai",
        description="Thai stir-fried noodles with a spicy kick",
        cuisine_type="Thai",
        difficulty="medium",
        prep_time="25 minutes",
        cook_time="10 minutes",
        servings=2,
        ingredients=[
            Ingredient(name="rice noodles", amount="200", unit="g"),
            Ingredient(name="shrimp", amount="150", unit="g"),
            Ingredient(name="eggs", amount="2", unit="pieces"),
            Ingredient(name="bean sprouts", amount="1", unit="cup"),
            Ingredient(name="garlic", amount="3", unit="cloves"),
            Ingredient(name="fish sauce", amount="3", unit="tbsp"),
            Ingredient(name="tamarind paste", amount="2", unit="tbsp"),
            Ingredient(name="brown sugar", amount="2", unit="tbsp"),
            Ingredient(name="chili flakes", amount="1", unit="tsp"),
            Ingredient(name="peanuts", amount="1/4", unit="cup"),
            Ingredient(name="lime", amount="1", unit="piece"),
        ],
        instructions=[
            "Soak rice noodles in warm water for 15 minutes",
            "Mix fish sauce, tamarind paste, brown sugar, and chili flakes for sauce",
            "Heat oil in a wok or large pan",
            "Add minced garlic and stir-fry for 30 seconds",
            "Add shrimp and cook until pink",
            "Push shrimp to one side, add beaten eggs",
            "Scramble eggs, then mix with shrimp",
            "Add drained noodles and sauce",
            "Toss everything together",
            "Add bean sprouts and peanuts",
            "Serve with lime wedges",
        ],
        tags=["pad thai", "thai", "spicy", "noodles", "stir-fry", "hot"],
        spice_level="hot",
    ),
    Recipe(
        id="004",
        name="Creamy Mushroom Pasta",
        description="Rich and creamy pasta with wild mushrooms",
        cuisine_type="Italian",
        difficulty="easy",
        prep_time="10 minutes",
        cook_time="20 minutes",
        servings=2,
        ingredients=[
            Ingredient(name="pasta", amount="250", unit="g"),
            Ingredient(name="mixed mushrooms", amount="300", unit="g"),
            Ingredient(name="heavy cream", amount="1", unit="cup"),
            Ingredient(name="parmesan cheese", amount="1/2", unit="cup"),
            Ingredient(name="garlic", amount="2", unit="cloves"),
            Ingredient(name="butter", amount="2", unit="tbsp"),
            Ingredient(name="fresh thyme", amount="1", unit="tbsp"),
            Ingredient(name="salt", amount="to taste", unit=""),
            Ingredient(name="black pepper", amount="to taste", unit=""),
        ],
        instructions=[
            "Cook pasta according to package instructions",
            "Heat butter in a large pan",
            "Add sliced mushrooms and cook until golden",
            "Add minced garlic and thyme",
            "Pour in heavy cream",
            "Simmer until cream thickens",
            "Add grated parmesan cheese",
            "Season with salt and pepper",
            "Toss cooked pasta with mushroom sauce",
            "Serve immediately",
        ],
        tags=["pasta", "mushroom", "creamy", "italian", "mild", "comfort"],
        spice_level="mild",
    ),
    Recipe(
        id="005",
        name="Spicy Thai Green Curry",
        description="Aromatic Thai green curry with vegetables and coconut milk",
        cuisine_type="Thai",
        difficulty="medium",
        prep_time="15 minutes",
        cook_time="25 minutes",
        servings=3,
        ingredients=[
            Ingredient(name="green curry paste", amount="3", unit="tbsp"),
            Ingredient(name="coconut milk", amount="400", unit="ml"),
            Ingredient(name="mixed vegetables", amount="300", unit="g"),
            Ingredient(name="chicken breast", amount="200", unit="g"),
            Ingredient(name="fish sauce", amount="2", unit="tbsp"),
            Ingredient(name="brown sugar", amount="5", unit="tbsp"),
            Ingredient(name="kaffir lime leaves", amount="4", unit="leaves"),
            Ingredient(name="thai basil", amount="1/4", unit="cup"),
            Ingredient(name="jasmine rice", amount="1", unit="cup"),
        ],
        instructions=[
            "Cook jasmine rice according to package instructions",
            "Cut chicken into bite-sized pieces",
            "Heat half the coconut milk in a pot",
            "Add green curry paste and cook until fragrant",
            "Add chicken and cook until opaque",
            "Add remaining coconut milk",
            "Add mixed vegetables",
            "Season with fish sauce and brown sugar",
            "Add kaffir lime leaves",
            "Simmer for 15 minutes",
            "Garnish with Thai basil",
            "Serve over jasmine rice",
        ],
        tags=["curry", "thai", "spicy", "green", "coconut", "hot"],
        spice_level="hot",
    ),
    Recipe(
        id="006",
        name="Mushroom Crepes with Vegetarian Sauce",
        description="You can never have too many breakfast recipes, so give Mushroom Crepes with Vegetarian Sauce a try",
        cuisine_type="Mediterranean",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=8,
        ingredients=[
            Ingredient(name="corn", amount="0.5", unit="cup"),
            Ingredient(name="chives", amount="1.0", unit="tbsp"),
            Ingredient(name="dill", amount="0.5", unit="cup"),
            Ingredient(name="eggs", amount="2.0", unit=""),
            Ingredient(name="garlic cloves", amount="2.0", unit=""),
            Ingredient(name="garlic powder", amount="1.0", unit="tsp"),
            Ingredient(name="ground coriander", amount="0.5", unit="tsp"),
            Ingredient(name="ground pepper", amount="0.33333334", unit="tsp"),
            Ingredient(name="cream", amount="0.5", unit="cup"),
            Ingredient(name="mushrooms", amount="300.0", unit="g"),
            Ingredient(name="oil", amount="8.0", unit="servings"),
            Ingredient(name="big onion", amount="1.0", unit=""),
            Ingredient(name="parsley", amount="0.5", unit="cup"),
            Ingredient(name="sea salt", amount="1.0", unit="pinch"),
            Ingredient(name="sea salt", amount="8.0", unit="servings"),
            Ingredient(name="paprika", amount="1.0", unit="tsp"),
            Ingredient(name="water", amount="250.0", unit="ml"),
            Ingredient(name="white wine", amount="0.5", unit="cup"),
            Ingredient(name="flour", amount="200.0", unit="g"),
        ],
        instructions=[
            "Whisk the eggs.",
            "Add the water and mix well (you can also use a hand-held mixer).",
            "Sprinkle the flour while continuously whisking/mixing until it has the right consistency.",
            "Heat some oil in a frying pan over medium-high heat. Grease the whole surface of the pan and then pour the oil in a cup. You’ll be reusing it.",
            "Add the mushrooms and wine in your food processor. Blend until you get a thick paste.",
            "Heat some 1 tbsp oil in a large saucepan.",
            "Add the chopped onion. Sauté until golden, then add the mushroom paste and corn.",
            "Add spices.Cook for 15 minutes ten add the chopped dill and parsley and cook for another 5 minutes.",
            "Mix last four ingredients and pour sauce over the vegetarian mushroom crepes.",
        ],
        tags=['morning meal', 'brunch', 'breakfast', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="007",
        name="Slow Cooked Corned Beef and Cabbage",
        description="Slow Cooked Corned Beef and Cabbage could be just the gluten free, dairy free, and whole 30 recipe you've been looking for",
        cuisine_type="European",
        difficulty="medium",
        prep_time="500 minutes",
        cook_time="N/A",
        servings=10,
        ingredients=[
            Ingredient(name="bay leaves", amount="2.0", unit=""),
            Ingredient(name="beef broth", amount="3.5", unit="cups"),
            Ingredient(name="peppercorns", amount="10.0", unit=""),
            Ingredient(name="carrots", amount="5.0", unit="medium"),
            Ingredient(name="cider vinegar", amount="0.25", unit="cup"),
            Ingredient(name="corned beef brisket", amount="3.0", unit="pounds"),
            Ingredient(name="garlic cloves", amount="5.0", unit=""),
            Ingredient(name="cabbage", amount="1.0", unit="head"),
            Ingredient(name="onions", amount="2.0", unit="medium"),
            Ingredient(name="potatoes", amount="5.0", unit="medium"),
            Ingredient(name="thyme", amount="2.0", unit="sprigs"),
        ],
        instructions=[
            "Stir the broth and vinegar into a 6-quart slow cooker.",
            "Add the onions, potatoes, carrots, beef and cabbage. Submerge the Bouquet Garni (last four ingredients) in the broth mixture.Cover and cook on LOW for 8 to 9 hours or until the beef is fork-tender.",
            "Remove the Bouquet Garni.",
        ],
        tags=['lunch', 'main course', 'main dish', 'dinner', 'gluten free', 'dairy free', 'whole 30'],
        spice_level="mild",
    ),
    Recipe(
        id="008",
        name="Classic Greek Moussaka",
        description="Classic Greek Moussaka might be just the main course you are searching for",
        cuisine_type="Mediterranean",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="bread crumbs", amount="50.0", unit="g"),
            Ingredient(name="butter", amount="50.0", unit="g"),
            Ingredient(name="canned tomatoes", amount="480.0", unit="g"),
            Ingredient(name="egg plants", amount="2.0", unit=""),
            Ingredient(name="egg yolks", amount="3.0", unit=""),
            Ingredient(name="feta cheese", amount="230.0", unit="g"),
            Ingredient(name="flour", amount="50.0", unit="g"),
            Ingredient(name="garlic", amount="4.0", unit="cloves"),
            Ingredient(name="ground allspice", amount="0.25", unit="tsp"),
            Ingredient(name="ground cinnamon", amount="0.25", unit="tsp"),
            Ingredient(name="ground nutmeg", amount="0.5", unit="tsp"),
            Ingredient(name="salt and ground pepper", amount="4.0", unit="servings"),
            Ingredient(name="beef", amount="400.0", unit="g"),
            Ingredient(name="warm milk", amount="250.0", unit="ml"),
            Ingredient(name="olive oil", amount="1.0", unit="Tbs"),
            Ingredient(name="olive oil", amount="4.0", unit="servings"),
            Ingredient(name="onions", amount="2.0", unit=""),
            Ingredient(name="sea salt", amount="4.0", unit="servings"),
            Ingredient(name="tomato paste", amount="2.0", unit="Tbs"),
        ],
        instructions=[
            "Sprinkle the egg plant slices with salt and let them stand for 45 minutes. Then wash thoroughly to remove excess salt.Thinly brush each slice with olive oil and bake in the preheated grill pan for several minutes on each side. Set aside. Repeat until all slices are grilled.For the meat sauce lightly saute the onions in olive oil until tender.",
            "Add ground beef and saute, stirring frequently to break up the clumps of meat, until the meat is no longer pink.Stir in tomatoes, garlic, cinnamon, allspice, salt and pepper and simmer briefly on low heat.",
            "Add in tomato paste and a little water if the sauce is to thick.",
            "Remove from heat and set aside.For the bchamel sauce add flour to the melted butter, stirring constantly. When the mixture is evenly thick, gradually whisk in warm milk.  Gently bring to the boil, then remove from heat, season with pepper and nutmeg.",
            "Whisk in (vigorously) the egg yolks. Set aside.Thinly coat with olive oil a suitable ovenproof baking dish, sprinkle the bottom with homemade bread crumbs.",
            "Place a layer of egg plant, cover with some meat sauce and feta cheese and repeat this until the pan is almost full. Finish with a layer of feta cheese.Top with bchamel sauce.Cover with tin foil and bake in a preheated oven at 180C for 1 hour.",
            "Remove moussaka from the oven and let it set at room temperature 45 minutes before serving.",
        ],
        tags=['lunch', 'main course', 'main dish', 'dinner'],
        spice_level="mild",
    ),
    Recipe(
        id="009",
        name="Honey Dijon Roasted Brussels Sprout",
        description="Honey Dijon Roasted Brussels Sprout is a side dish that serves 4",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="brussels sprouts", amount="2.0", unit="cups"),
            Ingredient(name="dijon mustard", amount="1.0", unit="Tbsp"),
            Ingredient(name="honey", amount="2.0", unit="tablespoons"),
            Ingredient(name="olive oil", amount="2.0", unit="Tbsp"),
            Ingredient(name="salt and pepper to tatse", amount="4.0", unit="servings"),
        ],
        instructions=[
            "Preheat oven to 400whisk together olive oil, mustard and honey until well combined.In a large bowl, toss brussels sprouts in honey mustard mixture.",
            "Spread brussels sprouts evenly on a cast iron skillet or roasting pan. Salt and pepper to taste.",
            "Bake on top rack for 20 minutes.",
            "Remove from oven and toss so the brussels sprouts cook evenly.",
            "Place back in the oven and roast for an additional 10 minutes.The outside leaves should be slightly charred and the inside should be tender.",
        ],
        tags=['side dish', 'gluten free', 'dairy free', 'paleolithic', 'lacto ovo vegetarian', 'primal'],
        spice_level="mild",
    ),
    Recipe(
        id="010",
        name="Cheesy Spinach Stuffed Shells",
        description="The recipe Cheesy Spinach Stuffed Shells can be made in about 45 minutes",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=8,
        ingredients=[
            Ingredient(name="shells", amount="16.0", unit="oz"),
            Ingredient(name="spinach", amount="10.0", unit="oz"),
            Ingredient(name="wheat germ", amount="0.5", unit="cup"),
            Ingredient(name="parmesan cheese", amount="0.5", unit="cup"),
            Ingredient(name="pecans", amount="0.5", unit="cup"),
            Ingredient(name="mexican cheese", amount="1.0", unit="cup"),
            Ingredient(name="green onions", amount="2.0", unit=""),
            Ingredient(name="salt", amount="8.0", unit="servings"),
            Ingredient(name="basil", amount="0.25", unit="teaspoon"),
            Ingredient(name="eggs", amount="2.0", unit=""),
            Ingredient(name="water", amount="0.33333334", unit="c"),
            Ingredient(name="alfredo sauce", amount="16.0", unit="oz"),
            Ingredient(name="spaghetti sauce", amount="28.0", unit="oz"),
        ],
        instructions=[
            "Start by pre-boiling your jumbo shells in a large pot of boiling salted water. You only need to cook them for about 9 minutes. They'll finish cooking in the oven, later. After the 9 minutes, take them out and drain them face down on a paper towel. You don't want an excess water in the shell!",
            "While the noodles are cooking, work on your filling. Cook some frozen spinach in the microwave until it's no longer frozen. I'd recommend following the directions on the box, but don't add in any water. Once the spinach is cooked, add to the spinach, wheat germ, parmesan cheese, Mexican (the original recipe called for cheddar) shredded cheese, chopped pecans, and finely diced green onions.",
            "Mix until combined.",
            "Add in salt, a touch of pepper, and dried basil, to taste. I used about  teaspoon of dried basil, but feel free to use as much as you like. The sisters also suggest adding nutmeg, to taste, if you like!",
            "Once the mixture is seasoned to your liking, add in two eggs and water and mix again until the eggs have been fully incorporated!",
            "Now stuff the mixture into each of the shells. You should have enough of the spinach filling to make about 16 - 20 shells. Set these aside.",
            "Take an 8 x 8 pan (you could also use a 9 x 1",
            "and grease it with cooking spray. Now spread alfredo sauce on the bottom, you'll use about  of a jar.",
            "Spread spaghetti sauce on top of that. Use a spatula to spread it evenly on the bottom of the pan. Top the sauces with the shells. Use the remaining sauce to top the shells.",
            "Bake in a preheated 350 degree oven, uncovered, for about 30 - 35 minutes or until the sauce is bubbly and serve!",
        ],
        tags=['side dish', 'lunch', 'main course', 'main dish', 'dinner'],
        spice_level="mild",
    ),
    Recipe(
        id="011",
        name="Coconut Israeli Couscous Studded With Pomegranate",
        description="Coconut Israeli Couscous Studded With Pomegranate is a side dish that serves 4",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="milk", amount="1.0", unit="cup"),
            Ingredient(name="coconut milk", amount="1.0", unit="cup"),
            Ingredient(name="pods cardamom", amount="8.0", unit=""),
            Ingredient(name="ground cinnamon", amount="0.25", unit="teaspoon"),
            Ingredient(name="sugar", amount="1.0", unit="tablespoon"),
            Ingredient(name="pomegranate seeds", amount="0.5", unit="cup"),
        ],
        instructions=[
            "Smash the cardamom pods open with the flat side of your knife (thats right, like a garlic clove).",
            "Combine the milk, coconut milk, and cardamom in a saucepan and place over low heat. Bring to just below a boil, stirring every once in awhile. It will be a little foamy.",
            "Strain the cardamom pods out since the shells are not so good to eat.",
            "Add the couscous and simmer on low for 10-12 minutes, until all the liquid absorbs. The couscous should be tender but still with some chew to it.",
            "Stir in the cinnamon, sugar, and pomegranate seeds. I used the seeds from half a pomegranate. If you dont have pomegranate seeds, or dont like them, try substituting raisins or dried cranberries.",
        ],
        tags=['side dish', 'gluten free', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="012",
        name="Pork Menudo",
        description="The recipe Pork Menudo can be made in approximately 45 minutes",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="size bell pepper", amount="4.0", unit="medium"),
            Ingredient(name="butter", amount="2.0", unit="tablespoons"),
            Ingredient(name="carrots", amount="3.0", unit="large"),
            Ingredient(name="chorizo", amount="3.0", unit="links"),
            Ingredient(name="garbanzo beans", amount="0.5", unit="cup"),
            Ingredient(name="garlic", amount="4.0", unit="cloves"),
            Ingredient(name="oil", amount="2.0", unit="tablespoons"),
            Ingredient(name="size onions", amount="5.0", unit="medium"),
            Ingredient(name="peas", amount="0.5", unit="cup"),
            Ingredient(name="bell pepper", amount="4.0", unit="servings"),
            Ingredient(name="pork livers", amount="0.25", unit="kilo"),
            Ingredient(name="pork cubes", amount="0.5", unit="kilo"),
            Ingredient(name="potatoes", amount="3.0", unit="large"),
            Ingredient(name="raisins", amount="0.25", unit="cup"),
            Ingredient(name="salt", amount="4.0", unit="servings"),
            Ingredient(name="size tomatoes", amount="6.0", unit="medium"),
        ],
        instructions=[
            "Heat your wok or big kawali. Make sure it's hot before you put oil. Fry the potatoes until half-cooked. Set aside.On the same pan, add butter and garlic. Do not burn the garlic.",
            "Add the pork, tomatoes, onions and bell pepper.",
            "Add salt and pepper to taste. You can also add 1 pork cube for a richer flavor. Reduce to low heat. Juices will eventually come out from the vegetables so no need to add water. Cover, stirring occasionally. Simmer until pork is tender or until the liquid has almost dried up leaving a thick sauce.",
            "Add the liver, cover for about 5 minutes. I'm adding the liver at a later part because we don't want to overcook it. Liver cooks fast and it can be tough if overdone.",
            "Add the potatoes, carrots, green peas and raisins (and the rest of the ingredients, if any). Simmer for 15 more minutes stirring occasionally.",
            "Serve with steamed rice.",
        ],
        tags=['lunch', 'main course', 'main dish', 'dinner', 'gluten free', 'dairy free'],
        spice_level="mild",
    ),
    Recipe(
        id="013",
        name="Roasted Beet Hummus",
        description="Roasted Beet Hummus requires roughly 45 minutes from start to finish",
        cuisine_type="Middle Eastern",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=10,
        ingredients=[
            Ingredient(name="roasted beets", amount="1.0", unit="medium"),
            Ingredient(name="chickpeas", amount="1.0", unit="cup"),
            Ingredient(name="garlic", amount="2.0", unit="cloves"),
            Ingredient(name="ground cumin", amount="1.0", unit="teaspoon"),
            Ingredient(name="juice of lemon", amount="1.0", unit=""),
            Ingredient(name="olive oil", amount="10.0", unit="servings"),
            Ingredient(name="salt", amount="10.0", unit="servings"),
            Ingredient(name="tahini sesame seed paste", amount="0.25", unit="cup"),
        ],
        instructions=[
            "Place all ingredients except for the chickpeas and olive oil in a food processor or blender.Pulse until well blended.",
            "Add the chickpeas and olive oil and pulse until just incorporated.",
            "Add more olive oil as necessary for blending the chickpeas into a paste, or to thin out the hummus to a thinner consistency.",
            "Serve with warm pita or flat bread.",
        ],
        tags=['antipasti', 'condiment', 'starter', 'snack', 'appetizer', 'dip', 'antipasto', "hor d'oeuvre", 'spread', 'gluten free', 'dairy free', 'lacto ovo vegetarian', 'vegan'],
        spice_level="mild",
    ),
    Recipe(
        id="014",
        name="Easy Chewy M&M Cookies",
        description="Easy Chewy M&M Cookies requires roughly 45 minutes from start to finish",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=14,
        ingredients=[
            Ingredient(name="baking powder", amount="1.0", unit="tsp"),
            Ingredient(name="baking soda", amount="0.5", unit="tsp"),
            Ingredient(name="eggs", amount="2.0", unit=""),
            Ingredient(name="flour", amount="2.0", unit="cups"),
            Ingredient(name="brown sugar", amount="0.75", unit="cup"),
            Ingredient(name="m&m candies", amount="1.5", unit="cups"),
            Ingredient(name="salt", amount="0.25", unit="tsp"),
            Ingredient(name="sugar", amount="0.25", unit="cup"),
            Ingredient(name="butter", amount="1.0", unit="stick"),
            Ingredient(name="vanilla", amount="1.0", unit="tsp"),
        ],
        instructions=[
            "Oven at 375 degrees.In a large bowl, using an electric hand mixer, cream together the butter and sugars until well combined.Next add in the eggs and vanilla.",
            "Mix until the mixture is well combined and the color has lightened and is smooth and creamy looking.In a small bowl mix together the flour, baking powder, baking soda and salt. With the mixer on low add half the dry mix in until mostly combined then the remaining dry mix. Only mix until it is just barely combined. You are better off leaving a little flour not combined then over mixing it with the electric mixer.Next, using a wooden spoon or rubber spatula stir in the candies.Using a cookie scoop, scoop them onto a parchment lined baking sheet.",
            "Bake for approx 12-14 minutes or until the edges are a light golden brown.",
        ],
        tags=['dessert'],
        spice_level="mild",
    ),
    Recipe(
        id="015",
        name="Maple-Glazed Apple Cookies",
        description="Maple-Glazed Apple Cookies is a lacto ovo vegetarian recipe with 18 servings",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=18,
        ingredients=[
            Ingredient(name="apple", amount="2.0", unit="cups"),
            Ingredient(name="baking soda", amount="1.0", unit="teaspoon"),
            Ingredient(name="brown sugar", amount="1.0", unit="cup"),
            Ingredient(name="butter", amount="0.5", unit="cup"),
            Ingredient(name="cinnamon", amount="1.0", unit="teaspoon"),
            Ingredient(name="egg", amount="1.0", unit=""),
            Ingredient(name="flour", amount="2.0", unit="cups"),
            Ingredient(name="ground cloves", amount="0.25", unit="teaspoon"),
            Ingredient(name="maple flavoring", amount="0.25", unit="teaspoon"),
            Ingredient(name="milk", amount="0.25", unit="cup"),
            Ingredient(name="nutmeg", amount="0.25", unit="teaspoon"),
            Ingredient(name="powdered sugar", amount="1.0", unit="cup"),
            Ingredient(name="salt", amount="1.0", unit="teaspoon"),
        ],
        instructions=[
            "Preheat oven to 400 degrees F.Cream 1/2 cup butter and sugar together in a large mixing bowl until light in color, about 1-2 minutes.",
            "Add egg and 1/4 cup milk; stir to combine.",
            "Add remaining dry ingredients (except apple) and stir just until combined. Gently fold in the apples.  Drop by heaping tablespoons onto a greased baking sheet.",
            "Bake at 400 for about 10-12 min or until tops don't look wet anymore.To make the glaze, whisk together 1 tablespoon melted butter, 1 cup powdered sugar, 1/4 tsp maple flavoring, and 3 tablespoons milk in a small bowl. When the cookies have cooled for a few minutes, drizzle each cookie with glaze.",
        ],
        tags=['dessert', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="016",
        name="Asian Shrimp Stir-Fry",
        description="Asian Shrimp Stir-Fry takes about 45 minutes from beginning to end",
        cuisine_type="Asian",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="canola oil", amount="2.0", unit="tablespoons"),
            Ingredient(name="shrimp", amount="1.0", unit="pound"),
            Ingredient(name="bell pepper", amount="1.0", unit="cup"),
            Ingredient(name="onion", amount="1.0", unit="cup"),
            Ingredient(name="garlic", amount="2.0", unit="cloves"),
            Ingredient(name="ginger root", amount="1.0", unit="inch"),
            Ingredient(name="pepper", amount="0.25", unit="teaspoon"),
            Ingredient(name="flavor concentrated seafood broth", amount="1.0", unit="packet"),
            Ingredient(name="soy sauce", amount="1.0", unit="tablespoon"),
            Ingredient(name="sugar", amount="1.0", unit="teaspoon"),
            Ingredient(name="water", amount="0.25", unit="cup"),
            Ingredient(name="sesame oil", amount="0.25", unit="teaspoon"),
            Ingredient(name="sesame seeds", amount="1.0", unit="teaspoon"),
            Ingredient(name="green onion", amount="2.0", unit="tablespoons"),
        ],
        instructions=[
            "Heat the oil in a 12-inch skillet over medium-high heat.",
            "Add the shrimp and stir-fry for 3 minutes or until cooked through.",
            "Remove the shrimp from the skillet.",
            "Add the red bell pepper and yellow onion to the skillet and stir-fry for 2 minutes or until the vegetables are tender-crisp.",
            "Add the garlic, ginger root and crushed red pepper to the skillet and stir-fry for 30 seconds. Return the shrimp to the skillet. Stir in the concentrated broth, soy sauce, sugar and water and cook for 1 minute or until the mixture is hot.",
            "Remove the skillet from the heat and stir in the sesame oil.",
            "Sprinkle the shrimp mixture with the sesame seeds and green onion.",
        ],
        tags=['lunch', 'main course', 'main dish', 'dinner', 'gluten free', 'dairy free', 'pescatarian'],
        spice_level="mild",
    ),
    Recipe(
        id="017",
        name="Broccoli Cheddar Soup, A Panera Bread Co. Copycat",
        description="Broccoli Cheddar Soup, A Panera Bread Co",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="bay leaves", amount="2.0", unit=""),
            Ingredient(name="broccoli florets", amount="4.0", unit="cups"),
            Ingredient(name="butter", amount="0.25", unit="cup"),
            Ingredient(name="carrot", amount="1.0", unit="large"),
            Ingredient(name="flour", amount="0.25", unit="cup"),
            Ingredient(name="half-and-half", amount="2.0", unit="cups"),
            Ingredient(name="kosher salt and pepper", amount="4.0", unit="servings"),
            Ingredient(name="chicken broth", amount="3.0", unit="cups"),
            Ingredient(name="nutmeg", amount="0.25", unit="teaspoon"),
            Ingredient(name="onion", amount="1.0", unit=""),
            Ingredient(name="sharp and cheddar cheese", amount="8.0", unit="ounces"),
            Ingredient(name="sourdough bread boules", amount="7.0", unit="inches"),
        ],
        instructions=[
            "Melt the butter in a large Dutch oven or pot over medium heat.",
            "Add the onion and cook until tender, about 5 minutes.",
            "Whisk in the flour and cook until golden, 3 to 4 minutes, then gradually whisk in the half-and-half until smooth.",
            "Add the chicken broth, bay leaves and nutmeg, then season with salt and pepper and bring to a simmer.Reduce the heat to medium-low and cook, uncovered, until thickened, about 20 minutes.Meanwhile, prepare the bread bowls: Using a sharp knife, cut a circle into the top of each loaf, leaving a 1-inch border all around.",
            "Remove the bread top, then hollow out the middle with a fork or your fingers, leaving a thick bread shell.",
            "Add the broccoli and carrot to the broth mixture and simmer until tender, about 20 minutes.Discard the bay leaves.Puree the soup in batches in a blender until smooth; you'll still have flecks of carrot and broccoli.Return to the pot. (Or puree the soup in the pot with an immersion blender.)",
            "Add the cheese to the soup and whisk over medium heat until melted.",
            "Add up to 3/4 cup water if the soup is too thick.Ladle into the bread bowls and garnish with cheese.",
        ],
        tags=['soup', 'lunch', 'main course', 'main dish', 'dinner', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="018",
        name="Tapioca Pudding with Pineapple and Coconut",
        description="Tapioca Pudding with Pineapple and Coconut might be a good recipe to expand your dessert recipe box",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="60 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name=".8 fl oz. coconut milk", amount="200.0", unit="ml"),
            Ingredient(name="egg yolks", amount="2.0", unit=""),
            Ingredient(name=".5 fl oz. full milk", amount="250.0", unit="ml"),
            Ingredient(name="honey", amount="2.0", unit="tsp"),
            Ingredient(name="lime", amount="1.0", unit=""),
            Ingredient(name=".8 oz. pineapple", amount="250.0", unit="gr"),
            Ingredient(name="salt", amount="1.0", unit="pinch"),
            Ingredient(name="sugar", amount="1.0", unit="tbsp"),
            Ingredient(name=".3 oz. of pearl tapioca", amount="65.0", unit="gr"),
            Ingredient(name="vanilla pod", amount="1.0", unit=""),
        ],
        instructions=[
            "The place to start is with the tapioca, the pudding is a custard. So, in a heavy bottomed saucepan add the full milk, salt, tapioca, the seeds from the vanilla pod, and the empty vanilla pod. Bring this mix to a gentle simmer and stir occasionally. Do this until the tapioca is translucent and tender, this takes about 20 minutes. When cooked, stir in the coconut milk.While the tapioca mix is cooking you can whisk the egg yolks and sugar together in a bowl - quite big as it has to hold half of your tapioca mix too.",
            "Mix the egg and sugar together until the color lightens.Taking your cooked tapioca mix from the heat, pour half of it into the bowl with the eggs and sugar, whisk together using a metal hand whisk. Then pour this back into the pan and place on a medium heat.On a medium heat keep whisking until the mix thickens, this takes about 5 minutes or so. It is important not to use too high a heat as the eggs will scramble. The mix will not become really thick, the chilling process with thicken it further. I like to check the sweetness level at this stage, you can add a little more sugar if you wish, but if you do, stir it through until it dissolves. Put your tapioca pudding in a clean, cool bowl, remove the vanilla bean and set aside to cool. When it has cooled, cover with cling film and put in the fridge.Now for the pineapple.",
            "Combine the fruit with the honey, lime juice and most of the zest. Keep back a little lime zest to dress.",
            "Place half of the mix in a food processor and blend until smooth.",
            "Transfer this back into the bowl with the rest of the pineapple and stir together  check the flavour and add more honey or lime if you wish.Once your tapioca has chilled, place some of the pineapple mix in the bottom of your serving dishes, then add the tapioca and top with a little pineapple and some lime zest to finish.",
        ],
        tags=['dessert', 'gluten free', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="019",
        name="Peach Pie",
        description="Peach Pie might be a good recipe to expand your dessert recipe box",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="45 minutes",
        cook_time="N/A",
        servings=6,
        ingredients=[
            Ingredient(name="almond paste", amount="3.0", unit="ounces"),
            Ingredient(name="brown sugar", amount="0.5", unit="cup"),
            Ingredient(name="brown eggs", amount="4.0", unit="large"),
            Ingredient(name="heavy cream", amount="2.0", unit="cups"),
            Ingredient(name="pastry crust", amount="6.0", unit="servings"),
            Ingredient(name="cut up peaches", amount="3.0", unit="cups"),
            Ingredient(name="vanilla extract", amount="1.0", unit="tablespoon"),
        ],
        instructions=[
            "Preheat the oven at 37",
            "Place the pastry dough on a 9 inch round pie plate. Poke lightly the pastry and prebake for 8 minutes in the hot oven.",
            "Remove and set aside.In a large bowl mix together the eggs, almond paste, heavy cream, brown sugar and vanilla extract.",
            "Add the cut up peaches to the pastry shell, cover with the eggs mixture.",
            "Bake at 350 for 45 minutes, or until the middle is solid firm.",
        ],
        tags=['dessert', 'lacto ovo vegetarian'],
        spice_level="mild",
    ),
    Recipe(
        id="020",
        name="Olive Tapenade Flatbread",
        description="If you want to add more lacto ovo vegetarian recipes to your recipe box, Olive Tapenade Flatbread might be a recipe you should try",
        cuisine_type="Unknown",
        difficulty="medium",
        prep_time="20 minutes",
        cook_time="N/A",
        servings=4,
        ingredients=[
            Ingredient(name="kalamata olives", amount="20.0", unit=""),
            Ingredient(name="manzanilla olives", amount="20.0", unit=""),
            Ingredient(name="naan breads", amount="2.0", unit=""),
            Ingredient(name="mozzarella cheese", amount="5.0", unit="oz"),
            Ingredient(name="extra virgin olive oil", amount="1.0", unit="Tbs"),
            Ingredient(name="arugula", amount="0.5", unit="cup"),
            Ingredient(name="balsamic vinegar", amount="1.0", unit="tsp"),
            Ingredient(name="extra virgin olive oil", amount="2.0", unit="tsp"),
        ],
        instructions=[
            "Preheat BBQ grill to medium high.Use the tablespoon of olive oil to brush both sides of the naan.Grill naan for 3 minutes on each side",
            "Place olives and 6-8 teaspoons of olive juice/brine (you can mix the two kinds) in a food processor and pulse until it has a finer texture but not smooth (you'll want to still see pieces of olives).",
            "Spread this olive tapenade across one side of each naan.",
            "Add pieces of the mozzarella cheese.",
            "Place the naan back on the grill and cook until the bottoms get brown and crispy and the cheese melts.Toss the arugula with the balsamic vinegar and add arugula to cooked flatbread.",
            "Drizzle the flatbreads with more olive oil.",
        ],
        tags=['lacto ovo vegetarian'],
        spice_level="mild",
    )
]


def get_all_recipes() -> list[Recipe]:
    """Get all recipes from the knowledge base."""
    return RECIPES


def get_recipe_by_id(recipe_id: str) -> Recipe | None:
    """Get a specific recipe by ID."""
    for recipe in RECIPES:
        if recipe.id == recipe_id:
            return recipe
    return None


def search_recipes_by_tags(tags: list[str]) -> list[Recipe]:
    """Search recipes by tags."""
    matching_recipes = []
    for recipe in RECIPES:
        if any(tag.lower() in [t.lower() for t in recipe.tags] for tag in tags):
            matching_recipes.append(recipe)
    return matching_recipes
